import sys
import os

# Ensure root folder is in python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

import numpy as np
import pandas as pd
from scipy.stats import ks_2samp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report
from xgboost import XGBClassifier
from sqlalchemy import text
from src.database.db_connection import get_db_engine


class ProbabilityOfDefaultEngine:
    """
    Probability of Default (PD) Modeling Engine:
    - Trains Logistic Regression (Regulatory Model) & XGBoost Classifier
    - Evaluates ROC-AUC, Gini Coefficient, and KS Statistic
    - Scales PD to Credit Scorecard Points (300 - 850)
    - Saves predictions to PostgreSQL
    """

    def __init__(self, woe_csv_path="data/credit_woe_transformed.csv"):
        self.engine = get_db_engine()
        self.woe_csv_path = woe_csv_path

    def load_data(self):
        """Loads WoE-transformed dataset generated by R."""
        if not os.path.exists(self.woe_csv_path):
            raise FileNotFoundError(f"❌ WoE dataset not found at {self.woe_csv_path}. Run R script first!")
        
        df = pd.read_csv(self.woe_csv_path)
        print(f"✅ Loaded WoE dataset with {len(df)} records.")
        return df

    @staticmethod
    def calculate_ks_stat(y_true, y_prob):
        """Calculates Kolmogorov-Smirnov (KS) Statistic."""
        defaults = y_prob[y_true == 1]
        non_defaults = y_prob[y_true == 0]
        ks_stat, _ = ks_2samp(defaults, non_defaults)
        return float(ks_stat)

    @staticmethod
    def calculate_scorecard_points(pd_val, target_score=600, target_odds=50, pts_double=20):
        """Converts PD into standard credit scorecard points (300 - 850 scale)."""
        pd_clipped = np.clip(pd_val, 0.0001, 0.9999)
        odds = (1.0 - pd_clipped) / pd_clipped
        factor = pts_double / np.log(2)
        offset = target_score - (factor * np.log(target_odds))
        score = offset + (factor * np.log(odds))
        return int(np.clip(score, 300, 850))

    def train_and_evaluate_models(self):
        """Trains Logistic Regression & XGBoost models and saves PD predictions."""
        df = self.load_data()

        # Target variable
        y = df['is_defaulted']
        
        # Features: Select WoE transformed features ending in _woe
        feature_cols = [c for c in df.columns if c.endswith('_woe')]
        if not feature_cols:
            # Fallback to numeric features excluding IDs and target
            feature_cols = [c for c in df.columns if c not in ['borrower_code', 'is_defaulted']]

        X = df[feature_cols]
        borrower_codes = df['borrower_code']

        # Train-Test Split (80% Train, 20% Test)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

        print(f"⚡ Training PD Models on {len(X_train)} training records...")

        # 1. Logistic Regression Model (Regulatory Standard)
        log_reg = LogisticRegression(max_iter=1000, C=1.0, random_state=42)
        log_reg.fit(X_train, y_train)
        
        y_pred_log_prob = log_reg.predict_proba(X_test)[:, 1]
        auc_log = roc_auc_score(y_test, y_pred_log_prob)
        gini_log = (2 * auc_log) - 1
        ks_log = self.calculate_ks_stat(y_test, y_pred_log_prob)

        # 2. XGBoost Model (Machine Learning Benchmark)
        xgb_model = XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.05, random_state=42, eval_metric='logloss')
        xgb_model.fit(X_train, y_train)

        y_pred_xgb_prob = xgb_model.predict_proba(X_test)[:, 1]
        auc_xgb = roc_auc_score(y_test, y_pred_xgb_prob)
        gini_xgb = (2 * auc_xgb) - 1
        ks_xgb = self.calculate_ks_stat(y_test, y_pred_xgb_prob)

        print("\n=======================================================")
        print("📊 PROBABILITY OF DEFAULT (PD) MODEL PERFORMANCE")
        print("=======================================================")
        print(f"1. Logistic Regression (Regulatory): AUC = {auc_log:.4f} | Gini = {gini_log:.4f} | KS = {ks_log*100:.2f}%")
        print(f"2. XGBoost Classifier (Benchmark):   AUC = {auc_xgb:.4f} | Gini = {gini_xgb:.4f} | KS = {ks_xgb*100:.2f}%")
        print("=======================================================\n")

        # Predict PD for FULL Dataset using Logistic Regression (Regulatory Model)
        full_pd_12m = log_reg.predict_proba(X)[:, 1]
        
        # Lifetime PD approximation under IFRS 9: Lifetime PD = 1 - (1 - PD_12m)^Term_Years
        # (Assuming average remaining term of 3 years)
        full_pd_lifetime = 1.0 - np.power(1.0 - full_pd_12m, 3.0)

        # Build Predictions DataFrame
        results = []
        for code, pd12, pd_lt in zip(borrower_codes, full_pd_12m, full_pd_lifetime):
            score_pts = self.calculate_scorecard_points(pd12)
            results.append({
                "borrower_code": code,
                "pd_12m": float(pd12),
                "pd_lifetime": float(pd_lt),
                "scorecard_points": score_pts,
                "model_type": "Logistic_Regression_WoE"
            })

        df_preds = pd.DataFrame(results)

        # Upload PD Predictions to PostgreSQL
        print(f"📥 Uploading {len(df_preds)} PD predictions to PostgreSQL...")
        with self.engine.begin() as conn:
            df_preds.to_sql("temp_pd_preds", conn, if_exists="replace", index=False)
            upsert_query = text("""
                INSERT INTO pd_model_predictions (borrower_code, pd_12m, pd_lifetime, scorecard_points, model_type)
                SELECT borrower_code, pd_12m, pd_lifetime, scorecard_points, model_type
                FROM temp_pd_preds
                ON CONFLICT (borrower_code) DO UPDATE
                SET pd_12m = EXCLUDED.pd_12m,
                    pd_lifetime = EXCLUDED.pd_lifetime,
                    scorecard_points = EXCLUDED.scorecard_points,
                    model_type = EXCLUDED.model_type;

                DROP TABLE temp_pd_preds;
            """)
            conn.execute(upsert_query)

        print("🎉 PD Model predictions and Credit Scorecard points saved to PostgreSQL!")

if __name__ == "__main__":
    pd_engine = ProbabilityOfDefaultEngine()
    pd_engine.train_and_evaluate_models()